"""Watched baskets across parallel industry-chain THEMES, plus a seed graph
(TechRoute nodes, alias tables, well-known structural edges) per theme.

Two active themes today:
  - ai_optical : AI optical-interconnect chain (optical modules, EML/DSP, customers)
  - ai_chip    : AI compute-chip chain (WFE/materials/EDA -> foundry -> memory/HBM
                 -> GPU/CPU -> advanced packaging -> PCB)

A company carries `themes` (it can belong to several) and `seg` (its segment id
per theme). New verticals = add a theme + companies here; nothing else changes.
"""
from __future__ import annotations

from ..ontology import EdgeType, NodeType, cycle
from ..ontology.cycle import CyclePosition as CP
from ..ontology.cycle import Cyclicality as CY

# --- Themes ----------------------------------------------------------------
# `kind` picks the organizing axis: "chain" = supply-chain tier (upstream→down),
# "cycle" = economic-cycle position (early→late/defensive). Cycle themes have no
# SEED_EDGES; their segments order along CYCLE_RANK instead of a chain tier.
THEMES: dict[str, dict] = {
    "ai_optical": {"name": "AI Optical Interconnect", "nameCn": "AI 光互连产业链", "kind": "chain"},
    "ai_chip": {"name": "AI Chip Supply Chain", "nameCn": "AI 算力芯片产业链", "kind": "chain"},
    "ai_software": {"name": "AI Software Adoption Chain", "nameCn": "AI 软件普及链", "kind": "chain"},
    "space_exploration": {"name": "Space Exploration", "nameCn": "太空探索产业链", "kind": "chain"},
    "humanoid_robotics": {"name": "Humanoid Robotics", "nameCn": "人形机器人产业链", "kind": "chain"},
    # consumer cycle themes (US-listed; organized by economic-cycle position, not a chain)
    "internet": {"name": "Internet Platforms", "nameCn": "互联网平台", "kind": "cycle"},
    "retail": {"name": "US Retail", "nameCn": "美国零售", "kind": "cycle"},
    "restaurants": {"name": "Restaurants & Foodservice", "nameCn": "餐饮服务", "kind": "cycle"},
}

# --- Segments (globally-unique ids; tier orders upstream -> downstream) -----
SEGMENTS: dict[str, dict] = {
    # ai_optical
    "upstream_component": {"name": "Upstream Components", "nameCn": "上游器件", "tier": 1, "theme": "ai_optical"},
    "module_maker": {"name": "Optical Module Makers", "nameCn": "光模块厂", "tier": 2, "theme": "ai_optical"},
    "contract_mfg": {"name": "Contract Manufacturing", "nameCn": "代工制造", "tier": 3, "theme": "ai_optical"},
    "downstream_customer": {"name": "Downstream Customers", "nameCn": "下游客户", "tier": 4, "theme": "ai_optical"},
    # ai_chip
    "chip_equipment": {"name": "WFE & Equipment", "nameCn": "晶圆厂设备", "tier": 1, "theme": "ai_chip"},
    "chip_materials": {"name": "Materials", "nameCn": "上游材料", "tier": 2, "theme": "ai_chip"},
    "chip_eda": {"name": "EDA & IP", "nameCn": "EDA / IP", "tier": 2, "theme": "ai_chip"},
    "chip_foundry": {"name": "Foundry", "nameCn": "晶圆代工", "tier": 3, "theme": "ai_chip"},
    "chip_memory": {"name": "Memory / HBM", "nameCn": "存储 / HBM", "tier": 4, "theme": "ai_chip"},
    "chip_gpu": {"name": "GPU / Accelerators", "nameCn": "GPU / 加速器", "tier": 5, "theme": "ai_chip"},
    "chip_cpu": {"name": "CPU", "nameCn": "CPU", "tier": 5, "theme": "ai_chip"},
    "chip_packaging": {"name": "Advanced Packaging", "nameCn": "先进封装", "tier": 6, "theme": "ai_chip"},
    "chip_pcb": {"name": "PCB / CCL", "nameCn": "PCB / 覆铜板", "tier": 7, "theme": "ai_chip"},
    # ai_software — tier = enterprise AI-adoption wave (early beneficiaries -> late)
    "swe_devinfra": {"name": "Dev & AI Infrastructure", "nameCn": "研发与AI基础设施", "tier": 1, "theme": "ai_software",
        "thesisCn": "普及第1浪：AI 编码助手/编码智能体最先放量，提交、流水线、制品、模型与密钥治理需求激增。用量制(CI分钟、扫描、存储、API调用)厂商率先受益——研发工具链是'建造智能体'的地方，最早兑现(如 JFrog 制品/模型仓库)。"},
    "swe_observability": {"name": "Observability & AIOps", "nameCn": "可观测 / AIOps", "tier": 2, "theme": "ai_software",
        "thesisCn": "普及第2浪：智能体进入生产即成为高风险新型负载，需要 LLM/Agent 可观测、评测与追踪；智能体本身又产生海量机器数据，与基础设施建设几乎同步受益(如 Datadog/Dynatrace)。"},
    "swe_data": {"name": "Data & AI Platforms", "nameCn": "数据与AI平台", "tier": 3, "theme": "ai_software",
        "thesisCn": "普及第3浪：RAG/企业搜索与智能体记忆需要向量+运营数据底座；数据治理与统一是企业级智能体落地的前置条件，用量随智能体流量增长。"},
    "swe_security": {"name": "Cybersecurity", "nameCn": "网络安全", "tier": 4, "theme": "ai_software",
        "thesisCn": "普及第4浪：AI 生成代码与非人类身份(智能体)扩大攻击面，带动代码到云的 DevSecOps、身份/密钥与数据安全；治理是放量的伴生刚需。"},
    "swe_productivity": {"name": "Collaboration & Productivity", "nameCn": "协作与生产力", "tier": 5, "theme": "ai_software",
        "thesisCn": "普及第5浪：Copilot 嵌入办公与工作流，按席位渗透；价值显性但替代周期较长，处于普及中段。"},
    "swe_crm": {"name": "CRM & Sales", "nameCn": "CRM / 销售", "tier": 6, "theme": "ai_software",
        "thesisCn": "普及第6浪：Agentforce 类销售/服务智能体重塑前台，但需流程与数据改造——距离 Salesforce 级普及尚需更长时间，晚于工具链放量。"},
    "swe_marketing": {"name": "Marketing & Creative", "nameCn": "营销与创意", "tier": 7, "theme": "ai_software",
        "thesisCn": "普及第7浪：生成式创意与 CDP/投放自动化提效显著，依赖数据与合规，处于中后段放量。"},
    "swe_erp_hr": {"name": "ERP / HR / Finance", "nameCn": "ERP / 人力 / 财务", "tier": 8, "theme": "ai_software",
        "thesisCn": "普及第8浪：后台系统改造重、合规要求高，智能体渗透最慢但 TAM 最大，属后期浪潮。"},
    "swe_vertical": {"name": "Vertical / Industry SaaS", "nameCn": "垂直行业 SaaS", "tier": 9, "theme": "ai_software",
        "thesisCn": "普及第9浪：行业 SaaS 需领域数据与监管适配，AI 价值兑现最晚，但壁垒与留存最强。"},
    # space_exploration — tier = upstream -> downstream of the space chain (SpaceX-centric)
    "spx_launch": {"name": "Launch Services & Rockets", "nameCn": "发射服务与运载火箭", "tier": 1, "theme": "space_exploration",
        "thesisCn": "最上游：每公斤入轨成本决定全链经济性。SpaceX(可复用 Falcon/Starship)垄断全球运力并设定价格底，公开纯标的稀缺且高弹性(Rocket Lab)。可复用与发射节奏是决定性变量。"},
    "spx_propulsion": {"name": "Propulsion & Engines", "nameCn": "推进系统与发动机", "tier": 2, "theme": "space_exploration",
        "thesisCn": "高壁垒核心：液体/固体主推进 + 上面级在轨推进 + 电推进。甲烷+可复用重塑成本曲线，电推进是卫星侧增速最快子段；军民两用带来稳定订单与单一来源风险。"},
    "spx_satellites": {"name": "Satellite & Constellation Mfg", "nameCn": "卫星与星座制造", "tier": 3, "theme": "space_exploration",
        "thesisCn": "巨型星座(Starlink 等)把卫星从定制品变为量产品，带动平台、载荷、相控阵与批量化制造；运营商与制造商分层，规模化制造是壁垒。"},
    "spx_datacenter": {"name": "Space Data Centers / Orbital Compute", "nameCn": "太空数据中心 / 在轨算力", "tier": 4, "theme": "space_exploration",
        "thesisCn": "主题核心——以 SpaceX 为代表的在轨/天基算力，利用太阳能与真空散热承载 AI 推理；尚处早期，受发射成本与功率/散热瓶颈制约，长期是天基 AI 基础设施。(不含地面数据中心)"},
    "spx_ground": {"name": "Ground Stations & Terminals", "nameCn": "地面站与用户终端", "tier": 5, "theme": "space_exploration",
        "thesisCn": "星座价值变现的关口——相控阵终端、地面站、Ground-Station-as-a-Service；随终端量产与下沉受益。"},
    "spx_components": {"name": "Space-grade Components & Materials", "nameCn": "航天级组件与材料", "tier": 6, "theme": "space_exploration",
        "thesisCn": "抗辐照芯片、星载电子、特种合金/复材、连接器——上游卡脖子环节，随发射节奏放量。"},
    "spx_apps": {"name": "EO / SATCOM / PNT Apps", "nameCn": "遥感/卫星通信/导航 应用", "tier": 7, "theme": "space_exploration",
        "thesisCn": "EO/SATCOM/PNT 下游应用与数据服务，最贴近终端付费；商业模式与数据壁垒决定成色。"},
    "spx_defense": {"name": "Space Defense Primes", "nameCn": "太空防务与系统集成", "tier": 8, "theme": "space_exploration",
        "thesisCn": "国防总集成商(primes)与太空军/防务系统，订单稳健、军民两用，是产业链下游的资金与系统枢纽。"},
    # humanoid_robotics — tier = upstream component -> downstream OEM integrator
    "hum_actuation": {"name": "Actuators / Reducers / Screws", "nameCn": "执行器/减速器/丝杠", "tier": 1, "theme": "humanoid_robotics",
        "thesisCn": "人形 BOM 最贵环节(执行器约 40-55%)，精密传动(谐波/RV/行星滚柱丝杠)是最稀缺高毛利部件。日本 Harmonic Drive 为高端基准，中国绿的谐波/双环传动以产能与价格快速替代；滚柱丝杠磨削良率是真瓶颈，Optimus/Figure 设计导入是二元催化。"},
    "hum_motors": {"name": "Frameless Torque Motors", "nameCn": "无框力矩电机", "tier": 2, "theme": "humanoid_robotics",
        "thesisCn": "关节的电磁心脏，无框转子+定子直嵌关节模组；约占整机 BOM 5-10%，扭矩密度/热/低齿槽决定关节成败。欧美设标杆，中国电机集群以价格加速国产替代。"},
    "hum_sensors": {"name": "Sensors (Force/Vision/IMU/Tactile)", "nameCn": "传感器(力/视觉/IMU/触觉)", "tier": 3, "theme": "humanoid_robotics",
        "thesisCn": "具身感知层——六维力/扭矩、视觉、IMU、触觉；触觉与力控是灵巧操作与安全的关键增量，单机用量随灵巧度上升。"},
    "hum_compute": {"name": "Onboard Compute & AI Brains", "nameCn": "域控/AI 大脑", "tier": 4, "theme": "humanoid_robotics",
        "thesisCn": "机器人'大脑'——车规级 SoC/GPU + 端侧 VLA 具身大模型；与 AI 算力链交叉，决定自主性与泛化能力。"},
    "hum_power": {"name": "Battery & Power Management", "nameCn": "电池与电源管理", "tier": 5, "theme": "humanoid_robotics",
        "thesisCn": "高倍率电池与电源管理决定续航与爆发力；对能量密度与安全要求高，模拟/电源芯片与电芯厂受益。"},
    "hum_hands": {"name": "Dexterous Hands / End-effectors", "nameCn": "灵巧手与末端执行", "tier": 6, "theme": "humanoid_robotics",
        "thesisCn": "灵巧手是操作能力上限的决定项，微型驱动+触觉+腱传动高度集成，价值量与技术壁垒双高。"},
    "hum_materials": {"name": "Lightweight Materials & Structures", "nameCn": "轻量化材料与结构件", "tier": 7, "theme": "humanoid_robotics",
        "thesisCn": "轻量化(PEEK/镁铝/碳纤)与结构件决定整机重量与能耗；随量产对成本与一致性要求提升。"},
    "hum_oem": {"name": "Humanoid OEM / Integrators", "nameCn": "本体整机与集成商", "tier": 8, "theme": "humanoid_robotics",
        "thesisCn": "整机厂/品牌集成商(Tesla Optimus、优必选、宇树等)是下游需求枢纽，拉动全链；多为私有或外采核心部件，上市纯标的有限。"},
}


def _cseg(name: str, nameCn: str, theme: str, pos: CP, cyc: CY, sens: float, thesisCn: str = "") -> dict:
    """Build a cycle-theme segment: `tier` IS the cycle rank, so the existing
    dashboard/heatmap ordering renders the early→late/defensive axis unchanged."""
    return {"name": name, "nameCn": nameCn, "theme": theme, "tier": cycle.rank(pos.value),
            "cycle": cycle.profile(pos, cyc, sens, noteCn=thesisCn), "thesisCn": thesisCn}


# Cycle-theme segments — ordered along CYCLE_RANK (early-cycle→late→defensive→
# counter-cyclical). Discount retail & QSR sit at the counter-cyclical end ("falls
# last / benefits from trade-down"), grocery/streaming are defensive, apparel/
# online-travel/casual-dining are early-cycle high-beta.
SEGMENTS.update({
    # --- internet (互联网平台) ---
    "net_travel": _cseg("Online Travel & Mobility", "在线旅游与出行", "internet", CP.EARLY, CY.CYCLICAL, 1.5,
        "在线旅游/OTA：纯可选消费、高弹性，复苏先行、衰退先跌；预订量是消费景气先行指标。"),
    "net_social": _cseg("Social & Advertising", "社交与广告", "internet", CP.EARLY, CY.CYCLICAL, 1.3,
        "广告型社交：品牌广告预算顺周期，景气下行最先削减；DAU/参与度与广告 eCPM 是先行量。"),
    "net_search_ads": _cseg("Search & Performance Ads", "搜索与效果广告", "internet", CP.MID, CY.CYCLICAL, 1.1,
        "搜索/效果广告：意图流量较抗跌（ROI 可量化），广告链中段；零售媒体为新增长极。"),
    "net_ecommerce": _cseg("E-commerce Platforms", "电商平台", "internet", CP.MID, CY.CYCLICAL, 1.2,
        "电商平台：可选消费为主，与零售周期同步；GMV/take-rate/履约成本决定单位经济。"),
    "net_gig": _cseg("Rideshare & Delivery", "出行与外卖", "internet", CP.EARLY, CY.CYCLICAL, 1.4,
        "出行/外卖平台：可选出行与配送，早周期高弹性；gross bookings 与 take-rate 顺周期。"),
    "net_fintech": _cseg("Payments & Fintech", "支付与金融科技", "internet", CP.MID, CY.CYCLICAL, 1.2,
        "支付/金融科技：支付额随消费波动、信贷敏感，顺周期中段；TPV/take-rate 是核心。"),
    "net_gaming": _cseg("Interactive Gaming", "互动游戏", "internet", CP.MID, CY.CYCLICAL, 1.0,
        "互动游戏：低价娱乐相对韧性、但新作驱动波动；bookings/MAU 与版号/上线节奏相关。"),
    "net_streaming": _cseg("Subscription Streaming", "订阅流媒体", "internet", CP.DEFENSIVE, CY.DEFENSIVE, 0.7,
        "订阅流媒体：订阅黏性高、低价居家娱乐，防御属性；订阅净增/churn/content spend 是关键。"),
    # --- retail (美国零售) ---
    "ret_apparel": _cseg("Apparel & Softlines", "服装与软线", "retail", CP.EARLY, CY.CYCLICAL, 1.4,
        "服装零售：纯可选、时尚库存风险高，景气下行最先承压；同店与库销比是先行量。"),
    "ret_electronics": _cseg("Electronics & Big-Ticket", "电器与大件", "retail", CP.EARLY, CY.CYCLICAL, 1.3,
        "电器/消费电子零售：大件可选、利率与换机周期敏感，早周期高弹性。"),
    "ret_home_improve": _cseg("Home Improvement", "家装零售", "retail", CP.MID, CY.CYCLICAL, 1.2,
        "家装零售：与房地产成交/利率周期相关，景气中段；客单与 Pro 业务决定韧性。"),
    "ret_specialty": _cseg("Specialty & Brand Retail", "专业与品牌零售", "retail", CP.MID, CY.CYCLICAL, 1.1,
        "专业/品牌零售（美妆、运动、宠物等）：可选品类，随消费周期；品牌力决定抗跌性。"),
    "ret_grocery": _cseg("Grocery & Staples Retail", "食品杂货零售", "retail", CP.DEFENSIVE, CY.DEFENSIVE, 0.5,
        "食品杂货：非可选刚需、最防御；同店客流稳、但毛利薄，受食品通胀与工资影响。"),
    "ret_auto_parts": _cseg("Auto Parts Retail", "汽配零售", "retail", CP.DEFENSIVE, CY.DEFENSIVE, 0.6,
        "汽配零售：经济疲弱时延长持车、以修代换，需求防御；车龄上升是结构顺风。"),
    "ret_discount": _cseg("Discount / Off-Price / Warehouse", "折扣/Off-Price/仓储会员", "retail", CP.COUNTER, CY.COUNTER_CYCLICAL, 0.6,
        "折扣/off-price/仓储会员：消费降级直接受益，下行最晚下跌、常逆势走强（用户点名：折扣零售最晚跌）。"),
    # --- restaurants (餐饮服务) ---
    "rst_casual_dining": _cseg("Casual Dining", "休闲正餐", "restaurants", CP.EARLY, CY.CYCLICAL, 1.4,
        "休闲正餐：可选堂食，景气下行最先收缩（客流先减、客单后压）；同店与客流是先行量。"),
    "rst_fine_dining": _cseg("Polished / Fine Dining", "精致/高端正餐", "restaurants", CP.EARLY, CY.CYCLICAL, 1.3,
        "高端正餐：高客单可选消费，宴请/商务需求顺周期；高端客群略具韧性但仍周期性。"),
    "rst_fast_casual": _cseg("Fast Casual", "快休闲", "restaurants", CP.MID, CY.CYCLICAL, 1.1,
        "快休闲（CMG/CAVA 类）：质价比可选，周期中段；单位经济与 AUV/新店增长是核心。"),
    "rst_coffee_snack": _cseg("Coffee & Snack", "咖啡与小食", "restaurants", CP.MID, CY.CYCLICAL, 1.0,
        "咖啡/小食：高频小额、介于可选与习惯刚需之间；客流与会员/数字化黏性决定韧性。"),
    "rst_pizza_delivery": _cseg("Pizza & Delivery", "披萨与外送", "restaurants", CP.DEFENSIVE, CY.DEFENSIVE, 0.8,
        "披萨/外送：高性价比便利餐，外卖韧性强，相对防御；数字化占比与单均配送成本是关键。"),
    "rst_qsr": _cseg("Quick-Service (QSR)", "快餐 (QSR)", "restaurants", CP.COUNTER, CY.COUNTER_CYCLICAL, 0.7,
        "快餐 QSR：消费降级受益（自正餐/在家做饭向下/向上挤压），下行相对抗跌、最晚承压。"),
})

# optical chain_role -> optical segment id
ROLE_TO_SEG = {
    "module_maker": "module_maker", "contract_manufacturer": "contract_mfg",
    "component": "upstream_component", "customer": "downstream_customer",
}


def _opt(c: dict) -> dict:
    """Default a single-theme optical company's themes/seg from its chain_role."""
    c.setdefault("themes", ["ai_optical"])
    c.setdefault("seg", {"ai_optical": ROLE_TO_SEG.get(c.get("chain_role"), "module_maker")})
    return c


# --- ai_optical companies (the original basket) ----------------------------
OPTICAL_COMPANIES: list[dict] = [_opt(c) for c in [
    {"id": "innolight", "name": "Innolight 中际旭创", "tickers": ["300308.SZ"],
     "aliases": ["中际旭创", "Zhongji Innolight", "Innolight", "旭创"], "region": "CN",
     "chain_role": "module_maker", "cn_code": "300308"},
    {"id": "eoptolink", "name": "Eoptolink 新易盛", "tickers": ["300502.SZ"],
     "aliases": ["新易盛", "Eoptolink"], "region": "CN", "chain_role": "module_maker", "cn_code": "300502"},
    {"id": "tspmd", "name": "T&S Communications 天孚通信", "tickers": ["300394.SZ"],
     "aliases": ["天孚通信", "T&S", "Tianfu", "天孚"], "region": "CN",
     "chain_role": "component", "cn_code": "300394"},
    {"id": "browave", "name": "Browave 博创科技", "tickers": ["300548.SZ"],
     "aliases": ["博创科技", "Browave"], "region": "CN", "chain_role": "module_maker", "cn_code": "300548"},
    {"id": "coherent", "name": "Coherent Corp", "tickers": ["COHR"],
     "aliases": ["Coherent", "II-VI", "II-VI Incorporated", "II-VI legacy"], "region": "US",
     "chain_role": "module_maker"},
    {"id": "lumentum", "name": "Lumentum Holdings", "tickers": ["LITE"],
     "aliases": ["Lumentum"], "region": "US", "chain_role": "component"},
    {"id": "fabrinet", "name": "Fabrinet", "tickers": ["FN"],
     "aliases": ["Fabrinet"], "region": "US", "chain_role": "contract_manufacturer"},
    {"id": "aaoi", "name": "Applied Optoelectronics", "tickers": ["AAOI"],
     "aliases": ["Applied Optoelectronics", "AOI"], "region": "US", "chain_role": "module_maker"},
    {"id": "arista", "name": "Arista Networks", "tickers": ["ANET"],
     "aliases": ["Arista", "Arista Networks"], "region": "US", "chain_role": "customer"},
    {"id": "cisco", "name": "Cisco Systems", "tickers": ["CSCO"],
     "aliases": ["Cisco"], "region": "US", "chain_role": "customer"},
]]

# Shared mega-caps belong to BOTH themes (optical role + chip GPU/ASIC).
SHARED_COMPANIES: list[dict] = [
    {"id": "nvidia", "name": "NVIDIA", "tickers": ["NVDA"], "aliases": ["NVIDIA", "Nvidia", "英伟达"],
     "region": "US", "chain_role": "customer", "themes": ["ai_optical", "ai_chip"],
     "seg": {"ai_optical": "downstream_customer", "ai_chip": "chip_gpu"}},
    {"id": "broadcom", "name": "Broadcom", "tickers": ["AVGO"], "aliases": ["Broadcom", "博通"],
     "region": "US", "chain_role": "component", "themes": ["ai_optical", "ai_chip"],
     "seg": {"ai_optical": "upstream_component", "ai_chip": "chip_gpu"}},
    {"id": "marvell", "name": "Marvell Technology", "tickers": ["MRVL"], "aliases": ["Marvell", "美满"],
     "region": "US", "chain_role": "component", "themes": ["ai_optical", "ai_chip"],
     "seg": {"ai_optical": "upstream_component", "ai_chip": "chip_gpu"}},
]


def _chip(cid, name, ticker, region, seg, aliases, cn_code=None) -> dict:
    return {"id": cid, "name": name, "tickers": [ticker], "aliases": aliases, "region": region,
            "chain_role": seg, "cn_code": cn_code, "themes": ["ai_chip"], "seg": {"ai_chip": seg}}


# --- ai_chip companies (full compute-chip supply chain) --------------------
CHIP_COMPANIES: list[dict] = [
    # WFE & equipment
    _chip("asml", "ASML 阿斯麦", "ASML", "US", "chip_equipment", ["ASML", "阿斯麦"]),
    _chip("amat", "Applied Materials 应用材料", "AMAT", "US", "chip_equipment", ["Applied Materials", "应用材料", "AMAT"]),
    _chip("lamresearch", "Lam Research 泛林", "LRCX", "US", "chip_equipment", ["Lam Research", "泛林", "LAM"]),
    _chip("klac", "KLA Corp 科磊", "KLAC", "US", "chip_equipment", ["KLA", "科磊"]),
    _chip("tokyoelectron", "Tokyo Electron 东京电子", "8035.T", "JP", "chip_equipment", ["Tokyo Electron", "东京电子", "TEL"]),
    _chip("advantest", "Advantest 爱德万测试", "6857.T", "JP", "chip_equipment", ["Advantest", "爱德万", "爱德万测试"]),
    # Materials
    _chip("shinetsu", "Shin-Etsu 信越化学", "4063.T", "JP", "chip_materials", ["Shin-Etsu", "信越化学", "信越"]),
    _chip("sumco", "SUMCO", "3436.T", "JP", "chip_materials", ["SUMCO", "胜高"]),
    _chip("entegris", "Entegris 英特格", "ENTG", "US", "chip_materials", ["Entegris", "英特格"]),
    _chip("nsig", "National Silicon 沪硅产业", "688126.SS", "CN", "chip_materials", ["沪硅产业", "National Silicon", "NSIG"], "688126"),
    # EDA & IP
    _chip("cadence", "Cadence 铿腾", "CDNS", "US", "chip_eda", ["Cadence", "铿腾"]),
    _chip("synopsys", "Synopsys 新思科技", "SNPS", "US", "chip_eda", ["Synopsys", "新思科技", "新思"]),
    _chip("arm", "Arm Holdings", "ARM", "US", "chip_eda", ["Arm", "ARM", "安谋"]),
    # Foundry
    _chip("tsmc", "TSMC 台积电", "TSM", "US", "chip_foundry", ["TSMC", "台积电", "台積電", "Taiwan Semiconductor"]),
    _chip("smic", "SMIC 中芯国际", "0981.HK", "HK", "chip_foundry", ["SMIC", "中芯国际", "中芯"]),
    _chip("globalfoundries", "GlobalFoundries 格芯", "GFS", "US", "chip_foundry", ["GlobalFoundries", "格芯", "GF"]),
    _chip("umc", "UMC 联华电子", "UMC", "US", "chip_foundry", ["UMC", "联华电子", "联电"]),
    # Memory / HBM
    _chip("skhynix", "SK Hynix 海力士", "000660.KS", "KR", "chip_memory", ["SK Hynix", "海力士", "SK海力士"]),
    _chip("micron", "Micron 美光", "MU", "US", "chip_memory", ["Micron", "美光"]),
    _chip("samsung", "Samsung Electronics 三星电子", "005930.KS", "KR", "chip_memory", ["Samsung", "三星电子", "三星"]),
    # GPU / accelerators (nvidia/broadcom/marvell shared above)
    _chip("amd", "AMD 超威", "AMD", "US", "chip_gpu", ["AMD", "超威", "Advanced Micro Devices"]),
    # CPU
    _chip("intel", "Intel 英特尔", "INTC", "US", "chip_cpu", ["Intel", "英特尔"]),
    _chip("qualcomm", "Qualcomm 高通", "QCOM", "US", "chip_cpu", ["Qualcomm", "高通"]),
    # Advanced packaging
    _chip("ase", "ASE Technology 日月光", "ASX", "US", "chip_packaging", ["ASE", "日月光", "ASE Technology"]),
    _chip("amkor", "Amkor 安靠", "AMKR", "US", "chip_packaging", ["Amkor", "安靠"]),
    # PCB / CCL
    _chip("shengyi", "Shengyi Tech 生益科技", "600183.SS", "CN", "chip_pcb", ["生益科技", "Shengyi", "生益"], "600183"),
    _chip("wuspcb", "WUS Printed Circuit 沪电股份", "002463.SZ", "CN", "chip_pcb", ["沪电股份", "WUS", "沪电"], "002463"),
    _chip("victorygiant", "Victory Giant 胜宏科技", "300476.SZ", "CN", "chip_pcb", ["胜宏科技", "Victory Giant", "胜宏"], "300476"),
    _chip("ibiden", "Ibiden", "4062.T", "JP", "chip_packaging", ["Ibiden", "揖斐电"]),
]

def _swe(cid, name, ticker, seg, aliases, region="US") -> dict:
    return {"id": cid, "name": name, "tickers": [ticker], "aliases": aliases, "region": region,
            "chain_role": seg, "cn_code": None, "themes": ["ai_software"], "seg": {"ai_software": seg}}


def _frontier(cid, name, ticker, region, seg, theme, aliases) -> dict:
    """Helper for space_exploration / humanoid_robotics names (global, region-aware)."""
    return {"id": cid, "name": name, "tickers": [ticker], "aliases": aliases, "region": region,
            "chain_role": seg, "cn_code": None, "themes": [theme], "seg": {theme: seg}}


# --- ai_software companies (Finnhub-verified US software >$2B; see scripts) ---
SOFTWARE_COMPANIES = [
    # --- swe_devinfra (wave 1) ---
    _swe("ibm", "IBM", "IBM", "swe_devinfra", ['IBM']),
    _swe("net", "Cloudflare", "NET", "swe_devinfra", ['Cloudflare', 'NET']),
    _swe("team", "Atlassian", "TEAM", "swe_devinfra", ['Atlassian', 'TEAM']),
    _swe("docn", "DigitalOcean", "DOCN", "swe_devinfra", ['DigitalOcean', 'DOCN']),
    _swe("ntnx", "Nutanix", "NTNX", "swe_devinfra", ['Nutanix', 'NTNX']),
    _swe("frog", "JFrog", "FROG", "swe_devinfra", ['JFrog', 'FROG']),
    _swe("path", "UiPath", "PATH", "swe_devinfra", ['UiPath', 'PATH']),
    _swe("gtlb", "GitLab", "GTLB", "swe_devinfra", ['GitLab', 'GTLB']),
    _swe("fsly", "Fastly", "FSLY", "swe_devinfra", ['Fastly', 'FSLY']),
    # --- swe_observability (wave 2) ---
    _swe("ddog", "Datadog", "DDOG", "swe_observability", ['Datadog', 'DDOG']),
    _swe("dt", "Dynatrace", "DT", "swe_observability", ['Dynatrace', 'DT']),
    _swe("ntct", "Netscout", "NTCT", "swe_observability", ['Netscout', 'NTCT']),
    # --- swe_data (wave 3) ---
    _swe("orcl", "Oracle", "ORCL", "swe_data", ['Oracle', 'ORCL']),
    _swe("pltr", "Palantir", "PLTR", "swe_data", ['Palantir', 'PLTR']),
    _swe("snow", "Snowflake", "SNOW", "swe_data", ['Snowflake', 'SNOW']),
    _swe("mdb", "MongoDB", "MDB", "swe_data", ['MongoDB', 'MDB']),
    _swe("cflt", "Confluent", "CFLT", "swe_data", ['Confluent', 'CFLT']),
    _swe("infa", "Informatica", "INFA", "swe_data", ['Informatica', 'INFA']),
    _swe("estc", "Elastic", "ESTC", "swe_data", ['Elastic', 'ESTC']),
    _swe("tdc", "Teradata", "TDC", "swe_data", ['Teradata', 'TDC']),
    # --- swe_security (wave 4) ---
    _swe("panw", "Palo Alto Networks", "PANW", "swe_security", ['Palo Alto Networks', 'PANW']),
    _swe("crwd", "CrowdStrike", "CRWD", "swe_security", ['CrowdStrike', 'CRWD']),
    _swe("ftnt", "Fortinet", "FTNT", "swe_security", ['Fortinet', 'FTNT']),
    _swe("zs", "Zscaler", "ZS", "swe_security", ['Zscaler', 'ZS']),
    _swe("ffiv", "F5", "FFIV", "swe_security", ['FFIV', 'F5']),
    _swe("cybr", "Cyberark", "CYBR", "swe_security", ['Cyberark', 'CYBR']),
    _swe("okta", "Okta", "OKTA", "swe_security", ['OKTA', 'Okta']),
    _swe("akam", "Akamai", "AKAM", "swe_security", ['Akamai', 'AKAM']),
    _swe("gen", "Gen Digital", "GEN", "swe_security", ['Gen Digital', 'GEN']),
    _swe("rbrk", "Rubrik", "RBRK", "swe_security", ['Rubrik', 'RBRK']),
    _swe("chkp", "Check Point", "CHKP", "swe_security", ['Check Point', 'CHKP']),
    _swe("sail", "SailPoint", "SAIL", "swe_security", ['SailPoint', 'SAIL']),
    _swe("s", "SentinelOne", "S", "swe_security", ['SentinelOne', 'S']),
    _swe("qlys", "Qualys", "QLYS", "swe_security", ['Qualys', 'QLYS']),
    _swe("vrns", "Varonis", "VRNS", "swe_security", ['Varonis', 'VRNS']),
    _swe("tenb", "Tenable", "TENB", "swe_security", ['Tenable', 'TENB']),
    # --- swe_productivity (wave 5) ---
    _swe("msft", "Microsoft", "MSFT", "swe_productivity", ['Microsoft', 'MSFT']),
    _swe("now", "ServiceNow", "NOW", "swe_productivity", ['ServiceNow', 'NOW']),
    _swe("zm", "Zoom", "ZM", "swe_productivity", ['Zoom', 'ZM']),
    _swe("docu", "DocuSign", "DOCU", "swe_productivity", ['DocuSign', 'DOCU']),
    _swe("smar", "Smartsheet", "SMAR", "swe_productivity", ['Smartsheet', 'SMAR']),
    _swe("dbx", "Dropbox", "DBX", "swe_productivity", ['Dropbox', 'DBX']),
    _swe("mndy", "monday.com", "MNDY", "swe_productivity", ['monday.com', 'MNDY']),
    _swe("box", "Box", "BOX", "swe_productivity", ['BOX', 'Box']),
    _swe("rng", "RingCentral", "RNG", "swe_productivity", ['RingCentral', 'RNG']),
    # --- swe_crm (wave 6) ---
    _swe("crm", "Salesforce", "CRM", "swe_crm", ['Salesforce', 'CRM']),
    _swe("hubs", "HubSpot", "HUBS", "swe_crm", ['HubSpot', 'HUBS']),
    _swe("zi", "ZoomInfo", "ZI", "swe_crm", ['ZoomInfo', 'ZI']),
    _swe("pega", "Pegasystems", "PEGA", "swe_crm", ['Pegasystems', 'PEGA']),
    _swe("frsh", "Freshworks", "FRSH", "swe_crm", ['Freshworks', 'FRSH']),
    # --- swe_marketing (wave 7) ---
    _swe("app", "Applovin", "APP", "swe_marketing", ['Applovin', 'APP']),
    _swe("adbe", "Adobe", "ADBE", "swe_marketing", ['Adobe', 'ADBE']),
    _swe("twlo", "Twilio", "TWLO", "swe_marketing", ['Twilio', 'TWLO']),
    _swe("gddy", "GoDaddy", "GDDY", "swe_marketing", ['GoDaddy', 'GDDY']),
    _swe("ttd", "Trade Desk", "TTD", "swe_marketing", ['Trade Desk', 'TTD']),
    _swe("zeta", "Zeta", "ZETA", "swe_marketing", ['Zeta', 'ZETA']),
    _swe("kvyo", "Klaviyo", "KVYO", "swe_marketing", ['Klaviyo', 'KVYO']),
    _swe("mgni", "Magnite", "MGNI", "swe_marketing", ['Magnite', 'MGNI']),
    _swe("brze", "Braze", "BRZE", "swe_marketing", ['Braze', 'BRZE']),
    _swe("ramp", "LiveRamp", "RAMP", "swe_marketing", ['LiveRamp', 'RAMP']),
    _swe("wix", "Wix", "WIX", "swe_marketing", ['WIX', 'Wix']),
    # --- swe_erp_hr (wave 8) ---
    _swe("sap", "SAP", "SAP", "swe_erp_hr", ['SAP']),
    _swe("adp", "ADP", "ADP", "swe_erp_hr", ['ADP']),
    _swe("intu", "Intuit", "INTU", "swe_erp_hr", ['Intuit', 'INTU']),
    _swe("wday", "Workday", "WDAY", "swe_erp_hr", ['Workday', 'WDAY']),
    _swe("payx", "Paychex", "PAYX", "swe_erp_hr", ['Paychex', 'PAYX']),
    _swe("day", "Dayforce", "DAY", "swe_erp_hr", ['Dayforce', 'DAY']),
    _swe("payc", "Paycom", "PAYC", "swe_erp_hr", ['Paycom', 'PAYC']),
    _swe("pcty", "Paylocity", "PCTY", "swe_erp_hr", ['Paylocity', 'PCTY']),
    _swe("pycr", "Paycor", "PYCR", "swe_erp_hr", ['Paycor', 'PYCR']),
    _swe("bill", "BILL", "BILL", "swe_erp_hr", ['BILL']),
    _swe("wk", "Workiva", "WK", "swe_erp_hr", ['Workiva', 'WK']),
    # --- swe_vertical (wave 9) ---
    # (DoorDash relocated to the `internet` cycle theme — net_gig; it is a gig/
    #  delivery platform, not enterprise SaaS.)
    _swe("veev", "Veeva", "VEEV", "swe_vertical", ['Veeva', 'VEEV']),
    _swe("iot", "Samsara", "IOT", "swe_vertical", ['Samsara', 'IOT']),
    _swe("tost", "Toast", "TOST", "swe_vertical", ['Toast', 'TOST']),
    _swe("tyl", "Tyler", "TYL", "swe_vertical", ['Tyler', 'TYL']),
    _swe("gwre", "Guidewire", "GWRE", "swe_vertical", ['Guidewire', 'GWRE']),
    _swe("bsy", "Bentley", "BSY", "swe_vertical", ['Bentley', 'BSY']),
    _swe("dsgx", "Descartes", "DSGX", "swe_vertical", ['Descartes', 'DSGX']),
    _swe("manh", "Manhattan Associates", "MANH", "swe_vertical", ['Manhattan Associates', 'MANH']),
    _swe("hqy", "Healthequity", "HQY", "swe_vertical", ['Healthequity', 'HQY']),
    _swe("cwan", "Clearwater Analytics", "CWAN", "swe_vertical", ['Clearwater Analytics', 'CWAN']),
    _swe("ttan", "ServiceTitan", "TTAN", "swe_vertical", ['ServiceTitan', 'TTAN']),
    _swe("pcor", "Procore", "PCOR", "swe_vertical", ['Procore', 'PCOR']),
    _swe("appf", "Appfolio", "APPF", "swe_vertical", ['Appfolio', 'APPF']),
    _swe("docs", "Doximity", "DOCS", "swe_vertical", ['Doximity', 'DOCS']),
    _swe("env", "Envestnet", "ENV", "swe_vertical", ['Envestnet', 'ENV']),
    _swe("soun", "SoundHound AI", "SOUN", "swe_vertical", ['SoundHound AI', 'SOUN']),
    _swe("qtwo", "Q2", "QTWO", "swe_vertical", ['QTWO', 'Q2']),
    _swe("spns", "Sapiens", "SPNS", "swe_vertical", ['Sapiens', 'SPNS']),
    _swe("agys", "Agilysys", "AGYS", "swe_vertical", ['Agilysys', 'AGYS']),
    _swe("payo", "Payoneer", "PAYO", "swe_vertical", ['Payoneer', 'PAYO']),
    _swe("alrm", "Alarm.com", "ALRM", "swe_vertical", ['Alarm.com', 'ALRM']),
    _swe("pinc", "Premier", "PINC", "swe_vertical", ['Premier', 'PINC']),
]

# --- space_exploration + humanoid_robotics companies (cap-verified) ---
SPACE_COMPANIES = [
    # --- spx_launch (tier 1) ---
    _frontier("rtx_spa", 'RTX Corporation', 'RTX', "US", "spx_launch", "space_exploration", ['RTX Corporation', 'RTX']),
    _frontier("ba_spa", 'Boeing', 'BA', "US", "spx_launch", "space_exploration", ['Boeing', 'BA']),
    _frontier("airpa_spa", 'Airbus SE', 'AIR.PA', "EU", "spx_launch", "space_exploration", ['Airbus SE', 'AIR.PA']),
    _frontier("safpa_spa", 'Safran SA', 'SAF.PA', "EU", "spx_launch", "space_exploration", ['Safran SA', 'SAF.PA']),
    _frontier("lmt_spa", 'Lockheed Martin', 'LMT', "US", "spx_launch", "space_exploration", ['Lockheed Martin', 'LMT']),
    _frontier("7011t_spa", 'Mitsubishi Heavy Industries', '7011.T', "JP", "spx_launch", "space_exploration", ['Mitsubishi Heavy Industries', '7011.T']),
    _frontier("noc_spa", 'Northrop Grumman', 'NOC', "US", "spx_launch", "space_exploration", ['Northrop Grumman', 'NOC']),
    _frontier("rklb_spa", 'Rocket Lab Corporation', 'RKLB', "US", "spx_launch", "space_exploration", ['Rocket Lab Corporation', 'RKLB']),
    _frontier("7013t_spa", 'IHI Corporation', '7013.T', "JP", "spx_launch", "space_exploration", ['IHI Corporation', '7013.T']),
    _frontier("600879ss_spa", 'China Aerospace Times Electronics', '600879.SS', "CN", "spx_launch", "space_exploration", ['China Aerospace Times Electronics', '600879.SS']),
    _frontier("fly_spa", 'Firefly Aerospace', 'FLY', "US", "spx_launch", "space_exploration", ['Firefly Aerospace', 'FLY']),
    _frontier("lunr_spa", 'Intuitive Machines', 'LUNR', "US", "spx_launch", "space_exploration", ['Intuitive Machines', 'LUNR']),
    _frontier("avijf_spa", 'AviChina Industry & Technology', 'AVIJF', "US", "spx_launch", "space_exploration", ['AviChina Industry & Technology', 'AVIJF']),
    _frontier("000901sz_spa", 'Aerospace Hi-Tech Holding Group', '000901.SZ', "CN", "spx_launch", "space_exploration", ['Aerospace Hi-Tech Holding Group', '000901.SZ']),
    _frontier("aviomi_spa", 'Avio S.p.A.', 'AVIO.MI', "EU", "spx_launch", "space_exploration", ['Avio S.p.A.', 'AVIO.MI']),
    # --- spx_propulsion (tier 2) ---
    _frontier("lhx_spa", 'L3Harris Technologies', 'LHX', "US", "spx_propulsion", "space_exploration", ['L3Harris Technologies', 'LHX']),
    _frontier("012450ks_spa", 'Hanwha Aerospace', '012450.KS', "KR", "spx_propulsion", "space_exploration", ['Hanwha Aerospace', '012450.KS']),
    _frontier("600893ss_spa", 'AECC Aviation Power', '600893.SS', "CN", "spx_propulsion", "space_exploration", ['AECC Aviation Power', '600893.SS']),
    _frontier("moga_spa", 'Moog Inc.', 'MOG-A', "US", "spx_propulsion", "space_exploration", ['Moog Inc.', 'MOG-A']),
    _frontier("krmn_spa", 'Karman Holdings Inc.', 'KRMN', "US", "spx_propulsion", "space_exploration", ['Karman Holdings Inc.', 'KRMN']),
    _frontier("600343ss_spa", 'Shaanxi Aerospace Power Hi-Tech', '600343.SS', "CN", "spx_propulsion", "space_exploration", ['Shaanxi Aerospace Power Hi-Tech', '600343.SS']),
    _frontier("003009sz_spa", 'Zhongtian Rocket', '003009.SZ', "CN", "spx_propulsion", "space_exploration", ['Zhongtian Rocket', '003009.SZ']),
    # --- spx_datacenter (tier 4) ---
    _frontier("688256ss_spa", 'Cambricon', '688256.SS', "CN", "spx_datacenter", "space_exploration", ['Cambricon', '688256.SS']),
    _frontier("6503t_spa", 'Mitsubishi Electric', '6503.T', "JP", "spx_datacenter", "space_exploration", ['Mitsubishi Electric', '6503.T']),
    _frontier("9432t_spa", 'NTT', '9432.T', "JP", "spx_datacenter", "space_exploration", ['NTT', '9432.T']),
    _frontier("mchp_spa", 'Microchip Technology', 'MCHP', "US", "spx_datacenter", "space_exploration", ['Microchip Technology', 'MCHP']),
    _frontier("asts_spa", 'AST SpaceMobile', 'ASTS', "US", "spx_datacenter", "space_exploration", ['AST SpaceMobile', 'ASTS']),
    _frontier("002281sz_spa", 'Accelink Technologies', '002281.SZ', "CN", "spx_datacenter", "space_exploration", ['Accelink Technologies', '002281.SZ']),
    _frontier("601698ss_spa", 'China Satcom', '601698.SS', "CN", "spx_datacenter", "space_exploration", ['China Satcom', '601698.SS']),
    _frontier("603019ss_spa", 'Sugon / Dawning Information', '603019.SS', "CN", "spx_datacenter", "space_exploration", ['Sugon / Dawning Information', '603019.SS']),
    _frontier("600118ss_spa", 'China Satellite (CASC)', '600118.SS', "CN", "spx_datacenter", "space_exploration", ['China Satellite (CASC)', '600118.SS']),
    _frontier("300223sz_spa", 'Ingenic (Beijing Junzheng)', '300223.SZ', "CN", "spx_datacenter", "space_exploration", ['Ingenic (Beijing Junzheng)', '300223.SZ']),
    _frontier("pl_spa", 'Planet Labs', 'PL', "US", "spx_datacenter", "space_exploration", ['Planet Labs', 'PL']),
    _frontier("688385ss_spa", 'Shanghai Fudan Microelectronics', '688385.SS', "CN", "spx_datacenter", "space_exploration", ['Shanghai Fudan Microelectronics', '688385.SS']),
    _frontier("9412t_spa", 'SKY Perfect JSAT', '9412.T', "JP", "spx_datacenter", "space_exploration", ['SKY Perfect JSAT', '9412.T']),
    _frontier("688568ss_spa", 'Geovis (Zhongke Xingtu)', '688568.SS', "CN", "spx_datacenter", "space_exploration", ['Geovis (Zhongke Xingtu)', '688568.SS']),
    _frontier("bksy_spa", 'BlackSky Technology', 'BKSY', "US", "spx_datacenter", "space_exploration", ['BlackSky Technology', 'BKSY']),
    # --- spx_ground (tier 5) ---
    _frontier("s63si_spa", 'ST Engineering', 'S63.SI', "SG", "spx_ground", "space_exploration", ['ST Engineering', 'S63.SI']),
    _frontier("6701t_spa", 'NEC / NTT-class SATCOM ground (Oki/NEC)', '6701.T', "JP", "spx_ground", "space_exploration", ['NEC / NTT-class SATCOM ground (Oki/NEC)', '6701.T']),
    _frontier("mtsi_spa", 'MACOM Technology Solutions', 'MTSI', "US", "spx_ground", "space_exploration", ['MACOM Technology Solutions', 'MTSI']),
    _frontier("047810ks_spa", 'Korea Aerospace Industries', '047810.KS', "KR", "spx_ground", "space_exploration", ['Korea Aerospace Industries', '047810.KS']),
    _frontier("ktos_spa", 'Kratos Defense & Security', 'KTOS', "US", "spx_ground", "space_exploration", ['Kratos Defense & Security', 'KTOS']),
    _frontier("vsat_spa", 'Viasat', 'VSAT', "US", "spx_ground", "space_exploration", ['Viasat', 'VSAT']),
    _frontier("qrvo_spa", 'Qorvo', 'QRVO', "US", "spx_ground", "space_exploration", ['Qorvo', 'QRVO']),
    _frontier("002405sz_spa", 'NavInfo / China space ground (CETC-affiliated)', '002405.SZ', "CN", "spx_ground", "space_exploration", ['NavInfo / China space ground (CETC-affiliated)', '002405.SZ']),
    _frontier("wolf_spa", 'Wolfspeed', 'WOLF', "US", "spx_ground", "space_exploration", ['Wolfspeed', 'WOLF']),
    _frontier("3596tw_spa", 'Arcadyan Technology', '3596.TW', "TW", "spx_ground", "space_exploration", ['Arcadyan Technology', 'Arcadyan', '3596.TW']),
    _frontier("gilt_spa", 'Gilat Satellite Networks', 'GILT', "US", "spx_ground", "space_exploration", ['Gilat Satellite Networks', 'GILT']),
    _frontier("300571sz_spa", 'Pingzhi Information', '300571.SZ', "CN", "spx_ground", "space_exploration", ['Pingzhi Information', '300571.SZ']),
    # --- spx_components (tier 6) ---
    _frontier("hwm_spa", 'Howmet Aerospace', 'HWM', "US", "spx_components", "space_exploration", ['Howmet Aerospace', 'HWM']),
    _frontier("crs_spa", 'Carpenter Technology', 'CRS', "US", "spx_components", "space_exploration", ['Carpenter Technology', 'CRS']),
    _frontier("ati_spa", 'ATI Inc.', 'ATI', "US", "spx_components", "space_exploration", ['ATI Inc.', 'ATI']),
    _frontier("002080sz_spa", 'Sinoma Science & Technology', '002080.SZ', "CN", "spx_components", "space_exploration", ['Sinoma Science & Technology', '002080.SZ']),
    _frontier("3402t_spa", 'Toray Industries', '3402.T', "JP", "spx_components", "space_exploration", ['Toray Industries', '3402.T']),
    _frontier("hxl_spa", 'Hexcel Corporation', 'HXL', "US", "spx_components", "space_exploration", ['Hexcel Corporation', 'HXL']),
    _frontier("mtrn_spa", 'Materion Corporation', 'MTRN', "US", "spx_components", "space_exploration", ['Materion Corporation', 'MTRN']),
    _frontier("688122ss_spa", 'Western Superconducting Technologies', '688122.SS', "CN", "spx_components", "space_exploration", ['Western Superconducting Technologies', '688122.SS']),
    _frontier("300699sz_spa", 'Weihai Guangwei Composites', '300699.SZ', "CN", "spx_components", "space_exploration", ['Weihai Guangwei Composites', '300699.SZ']),
    _frontier("3401t_spa", 'Teijin Limited', '3401.T', "JP", "spx_components", "space_exploration", ['Teijin Limited', '3401.T']),
    _frontier("600456ss_spa", 'Baoji Titanium (Baoti Group)', '600456.SS', "CN", "spx_components", "space_exploration", ['Baoji Titanium (Baoti Group)', '600456.SS']),
    _frontier("300034sz_spa", 'Gaona Aero Material (GoHigh)', '300034.SZ', "CN", "spx_components", "space_exploration", ['Gaona Aero Material (GoHigh)', '300034.SZ']),
    _frontier("mrnpa_spa", 'Mersen SA', 'MRN.PA', "EU", "spx_components", "space_exploration", ['Mersen SA', 'MRN.PA']),
    # --- spx_apps (tier 7) ---
    _frontier("grmn_spa", 'Garmin', 'GRMN', "US", "spx_apps", "space_exploration", ['Garmin', 'GRMN']),
    _frontier("sats_spa", 'EchoStar', 'SATS', "US", "spx_apps", "space_exploration", ['EchoStar', 'SATS']),
    _frontier("hxgby_spa", 'Hexagon AB', 'HXGBY', "US", "spx_apps", "space_exploration", ['Hexagon AB', 'HXGBY']),
    _frontier("trmb_spa", 'Trimble', 'TRMB', "US", "spx_apps", "space_exploration", ['Trimble', 'TRMB']),
    _frontier("gsat_spa", 'Globalstar', 'GSAT', "US", "spx_apps", "space_exploration", ['Globalstar', 'GSAT']),
    _frontier("irdm_spa", 'Iridium Communications', 'IRDM', "US", "spx_apps", "space_exploration", ['Iridium Communications', 'IRDM']),
    _frontier("etlpa_spa", 'Eutelsat Communications', 'ETL.PA', "EU", "spx_apps", "space_exploration", ['Eutelsat Communications', 'ETL.PA']),
    _frontier("002151sz_spa", 'Beijing BDStar Navigation', '002151.SZ', "CN", "spx_apps", "space_exploration", ['Beijing BDStar Navigation', '002151.SZ']),
    _frontier("300045sz_spa", 'Hwa Create', '300045.SZ', "CN", "spx_apps", "space_exploration", ['Hwa Create', '300045.SZ']),
    _frontier("satl_spa", 'Satellogic', 'SATL', "US", "spx_apps", "space_exploration", ['Satellogic', 'SATL']),
    # --- spx_defense (tier 8) ---
    _frontier("gd_spa", 'General Dynamics', 'GD', "US", "spx_defense", "space_exploration", ['General Dynamics', 'GD']),
    _frontier("hopa_spa", 'Thales', 'HO.PA', "EU", "spx_defense", "space_exploration", ['Thales', 'HO.PA']),
    _frontier("eslt_spa", 'Elbit Systems', 'ESLT', "US", "spx_defense", "space_exploration", ['Elbit Systems', 'ESLT']),
    _frontier("ldomi_spa", 'Leonardo', 'LDO.MI', "EU", "spx_defense", "space_exploration", ['Leonardo', 'LDO.MI']),
    _frontier("saabbst_spa", 'Saab AB', 'SAAB-B.ST', "SE", "spx_defense", "space_exploration", ['Saab AB', 'SAAB-B.ST']),
    _frontier("voyg_spa", 'Voyager Technologies', 'VOYG', "US", "spx_defense", "space_exploration", ['Voyager Technologies', 'VOYG']),
]

ROBOT_COMPANIES = [
    # --- hum_actuation (tier 1) ---
    _frontier("601100ss_hum", 'Jiangsu Hengli Hydraulic (恒立液压)', '601100.SS', "CN", "hum_actuation", "humanoid_robotics", ['Jiangsu Hengli Hydraulic (恒立液压)', '601100.SS', '恒立液压']),
    _frontier("6594t_hum", 'Nidec', '6594.T', "JP", "hum_actuation", "humanoid_robotics", ['Nidec', '6594.T']),
    _frontier("688017ss_hum", 'Leader Harmonious Drive (绿的谐波)', '688017.SS', "CN", "hum_actuation", "humanoid_robotics", ['Leader Harmonious Drive (绿的谐波)', '688017.SS', '绿的谐波']),
    _frontier("sha0de_hum", 'Schaeffler', 'SHA0.DE', "EU", "hum_actuation", "humanoid_robotics", ['Schaeffler', 'SHA0.DE']),
    _frontier("002472sz_hum", 'Zhejiang Shuanghuan Driveline (双环传动)', '002472.SZ', "CN", "hum_actuation", "humanoid_robotics", ['Zhejiang Shuanghuan Driveline (双环传动)', '002472.SZ', '双环传动']),
    _frontier("6324t_hum", 'Harmonic Drive Systems', '6324.T', "JP", "hum_actuation", "humanoid_robotics", ['Harmonic Drive Systems', '6324.T']),
    _frontier("003021sz_hum", 'Shenzhen Zhaowei (兆威机电)', '003021.SZ', "CN", "hum_actuation", "humanoid_robotics", ['Shenzhen Zhaowei (兆威机电)', '003021.SZ', '兆威机电']),
    _frontier("603667ss_hum", 'Wuzhou Xinchun (五洲新春)', '603667.SS', "CN", "hum_actuation", "humanoid_robotics", ['Wuzhou Xinchun (五洲新春)', '603667.SS', '五洲新春']),
    _frontier("002896sz_hum", 'Ningbo Zhongda Leader (中大力德)', '002896.SZ', "CN", "hum_actuation", "humanoid_robotics", ['Ningbo Zhongda Leader (中大力德)', '002896.SZ', '中大力德']),
    _frontier("603009ss_hum", 'Beite Technology (北特科技)', '603009.SS', "CN", "hum_actuation", "humanoid_robotics", ['Beite Technology (北特科技)', '603009.SS', '北特科技']),
    _frontier("300580sz_hum", 'Best Precision (贝斯特)', '300580.SZ', "CN", "hum_actuation", "humanoid_robotics", ['Best Precision (贝斯特)', '300580.SZ', '贝斯特']),
    _frontier("688160ss_hum", 'Kinco / Boketech (步科股份)', '688160.SS', "CN", "hum_actuation", "humanoid_robotics", ['Kinco / Boketech (步科股份)', '688160.SS', '步科股份']),
    # --- hum_motors (tier 2) ---
    _frontier("ph_hum", 'Parker-Hannifin', 'PH', "US", "hum_motors", "humanoid_robotics", ['Parker-Hannifin', 'PH']),
    _frontier("002008sz_hum", "Han's Laser (大族激光 / 大族电机)", '002008.SZ', "CN", "hum_motors", "humanoid_robotics", ["Han's Laser (大族激光 / 大族电机)", '002008.SZ', '大族激光']),
    _frontier("600580ss_hum", 'Wolong Electric Drive (卧龙电驱)', '600580.SS', "CN", "hum_motors", "humanoid_robotics", ['Wolong Electric Drive (卧龙电驱)', '600580.SS', '卧龙电驱']),
    _frontier("st_hum", 'Sensata Technologies (BEI Kimco)', 'ST', "US", "hum_motors", "humanoid_robotics", ['Sensata Technologies (BEI Kimco)', 'ST']),
    _frontier("novt_hum", 'Novanta Inc. (Celera Motion)', 'NOVT', "US", "hum_motors", "humanoid_robotics", ['Novanta Inc. (Celera Motion)', 'NOVT']),
    _frontier("603728ss_hum", "Moons'/Mingzhi Electric (鸣志电器)", '603728.SS', "CN", "hum_motors", "humanoid_robotics", ["Moons'/Mingzhi Electric (鸣志电器)", '603728.SS', '鸣志电器']),
    _frontier("300503sz_hum", 'Haozhi Mechanical & Electric (昊志机电)', '300503.SZ', "CN", "hum_motors", "humanoid_robotics", ['Haozhi Mechanical & Electric (昊志机电)', '300503.SZ', '昊志机电']),
    _frontier("002979sz_hum", 'Leadshine / Leisai Intelligent (雷赛智能)', '002979.SZ', "CN", "hum_motors", "humanoid_robotics", ['Leadshine / Leisai Intelligent (雷赛智能)', '002979.SZ', '雷赛智能']),
    _frontier("300660sz_hum", 'Jiangsu Leili (江苏雷利)', '300660.SZ', "CN", "hum_motors", "humanoid_robotics", ['Jiangsu Leili (江苏雷利)', '300660.SZ', '江苏雷利']),
    _frontier("688698ss_hum", 'Veichi Electric (伟创电气)', '688698.SS', "CN", "hum_motors", "humanoid_robotics", ['Veichi Electric (伟创电气)', '688698.SS', '伟创电气']),
    _frontier("alnt_hum", 'Allient Inc. (Allied Motion)', 'ALNT', "US", "hum_motors", "humanoid_robotics", ['Allient Inc. (Allied Motion)', 'ALNT']),
    # --- hum_sensors (tier 3) ---
    _frontier("6981t_hum", 'Murata Manufacturing', '6981.T', "JP", "hum_sensors", "humanoid_robotics", ['Murata Manufacturing', '6981.T']),
    _frontier("6758t_hum", 'Sony Group', '6758.T', "JP", "hum_sensors", "humanoid_robotics", ['Sony Group', '6758.T']),
    _frontier("6861t_hum", 'Keyence', '6861.T', "JP", "hum_sensors", "humanoid_robotics", ['Keyence', '6861.T']),
    _frontier("stm_hum", 'STMicroelectronics', 'STM', "US", "hum_sensors", "humanoid_robotics", ['STMicroelectronics', 'STM']),
    _frontier("6762t_hum", 'TDK (InvenSense)', '6762.T', "JP", "hum_sensors", "humanoid_robotics", ['TDK (InvenSense)', '6762.T']),
    _frontier("603501ss_hum", 'Will Semiconductor / 韦尔股份 (OmniVision)', '603501.SS', "CN", "hum_sensors", "humanoid_robotics", ['Will Semiconductor / 韦尔股份 (OmniVision)', '603501.SS', '韦尔股份']),
    _frontier("algm_hum", 'Allegro MicroSystems', 'ALGM', "US", "hum_sensors", "humanoid_robotics", ['Allegro MicroSystems', 'ALGM']),
    _frontier("688322ss_hum", 'Orbbec / 奥比中光', '688322.SS', "CN", "hum_sensors", "humanoid_robotics", ['Orbbec / 奥比中光', '688322.SS', '奥比中光']),
    _frontier("688213ss_hum", 'SmartSens / 思特威', '688213.SS', "CN", "hum_sensors", "humanoid_robotics", ['SmartSens / 思特威', '688213.SS', '思特威']),
    _frontier("688582ss_hum", 'Chipsea / 芯动联科 (Microsystems)', '688582.SS', "CN", "hum_sensors", "humanoid_robotics", ['Chipsea / 芯动联科 (Microsystems)', '688582.SS', '芯动联科']),
    _frontier("603662ss_hum", 'Keli Sensing / 柯力传感', '603662.SS', "CN", "hum_sensors", "humanoid_robotics", ['Keli Sensing / 柯力传感', '603662.SS', '柯力传感']),
    _frontier("300007sz_hum", 'Hanwei Technology / 汉威科技', '300007.SZ', "CN", "hum_sensors", "humanoid_robotics", ['Hanwei Technology / 汉威科技', '300007.SZ', '汉威科技']),
    _frontier("301413sz_hum", 'Ampron / 安培龙', '301413.SZ', "CN", "hum_sensors", "humanoid_robotics", ['Ampron / 安培龙', '301413.SZ', '安培龙']),
    _frontier("605488ss_hum", 'Fulai New Material / 福莱新材', '605488.SS', "CN", "hum_sensors", "humanoid_robotics", ['Fulai New Material / 福莱新材', '605488.SS', '福莱新材']),
    _frontier("090710kq_hum", 'Robotous', '090710.KQ', "KR", "hum_sensors", "humanoid_robotics", ['Robotous', '090710.KQ']),
    # --- hum_compute (tier 4) ---
    _frontier("2330tw_hum", 'TSMC', '2330.TW', "TW", "hum_compute", "humanoid_robotics", ['TSMC', '2330.TW']),
    _frontier("6723t_hum", 'Renesas Electronics', '6723.T', "JP", "hum_compute", "humanoid_robotics", ['Renesas Electronics', '6723.T']),
    _frontier("6702t_hum", 'Fujitsu', '6702.T', "JP", "hum_compute", "humanoid_robotics", ['Fujitsu', '6702.T']),
    _frontier("603893ss_hum", 'Rockchip (瑞芯微)', '603893.SS', "CN", "hum_compute", "humanoid_robotics", ['Rockchip (瑞芯微)', '603893.SS', '瑞芯微']),
    _frontier("9660hk_hum", 'Horizon Robotics', '9660.HK', "HK", "hum_compute", "humanoid_robotics", ['Horizon Robotics', '9660.HK']),
    _frontier("688099ss_hum", 'Amlogic (晶晨)', '688099.SS', "CN", "hum_compute", "humanoid_robotics", ['Amlogic (晶晨)', '688099.SS', '晶晨']),
    _frontier("300458sz_hum", 'Allwinner Technology (全志)', '300458.SZ', "CN", "hum_compute", "humanoid_robotics", ['Allwinner Technology (全志)', '300458.SZ', '全志']),
    _frontier("300496sz_hum", 'ThunderSoft (中科创达)', '300496.SZ', "CN", "hum_compute", "humanoid_robotics", ['ThunderSoft (中科创达)', '300496.SZ', '中科创达']),
    _frontier("amba_hum", 'Ambarella', 'AMBA', "US", "hum_compute", "humanoid_robotics", ['Ambarella', 'AMBA']),
    _frontier("6526t_hum", 'Socionext', '6526.T', "JP", "hum_compute", "humanoid_robotics", ['Socionext', '6526.T']),
    _frontier("688088ss_hum", 'ArcSoft (虹软)', '688088.SS', "CN", "hum_compute", "humanoid_robotics", ['ArcSoft (虹软)', '688088.SS', '虹软']),
    # --- hum_power (tier 5) ---
    _frontier("txn_hum", 'Texas Instruments', 'TXN', "US", "hum_power", "humanoid_robotics", ['Texas Instruments', 'TXN']),
    _frontier("300750sz_hum", 'CATL (Contemporary Amperex)', '300750.SZ', "CN", "hum_power", "humanoid_robotics", ['CATL (Contemporary Amperex)', '300750.SZ']),
    _frontier("adi_hum", 'Analog Devices', 'ADI', "US", "hum_power", "humanoid_robotics", ['Analog Devices', 'ADI']),
    _frontier("ifxde_hum", 'Infineon Technologies', 'IFX.DE', "EU", "hum_power", "humanoid_robotics", ['Infineon Technologies', 'IFX.DE']),
    _frontier("mpwr_hum", 'Monolithic Power Systems', 'MPWR', "US", "hum_power", "humanoid_robotics", ['Monolithic Power Systems', 'MPWR']),
    _frontier("373220ks_hum", 'LG Energy Solution', '373220.KS', "KR", "hum_power", "humanoid_robotics", ['LG Energy Solution', '373220.KS']),
    _frontier("006400ks_hum", 'Samsung SDI', '006400.KS', "KR", "hum_power", "humanoid_robotics", ['Samsung SDI', '006400.KS']),
    _frontier("300014sz_hum", 'EVE Energy 亿纬锂能', '300014.SZ', "CN", "hum_power", "humanoid_robotics", ['EVE Energy 亿纬锂能', '300014.SZ', '亿纬锂能']),
    _frontier("688141ss_hum", 'Joulwatt 杰华特', '688141.SS', "CN", "hum_power", "humanoid_robotics", ['Joulwatt 杰华特', '688141.SS', '杰华特']),
    _frontier("688052ss_hum", 'NOVOSENSE 纳芯微', '688052.SS', "CN", "hum_power", "humanoid_robotics", ['NOVOSENSE 纳芯微', '688052.SS', '纳芯微']),
    _frontier("300207sz_hum", 'Sunwoda Electronic 欣旺达', '300207.SZ', "CN", "hum_power", "humanoid_robotics", ['Sunwoda Electronic 欣旺达', '300207.SZ', '欣旺达']),
    _frontier("688772ss_hum", 'Zhuhai CosMX Battery 珠海冠宇', '688772.SS', "CN", "hum_power", "humanoid_robotics", ['Zhuhai CosMX Battery 珠海冠宇', '688772.SS', '珠海冠宇']),
    # --- hum_hands (tier 6) ---
    _frontier("601689ss_hum", 'Tuopu Group 拓普集团', '601689.SS', "CN", "hum_hands", "humanoid_robotics", ['Tuopu Group 拓普集团', '601689.SS', '拓普集团']),
    _frontier("6479t_hum", 'MinebeaMitsumi', '6479.T', "JP", "hum_hands", "humanoid_robotics", ['MinebeaMitsumi', '6479.T']),
    _frontier("300115sz_hum", 'Everwin Precision 长盈精密', '300115.SZ', "CN", "hum_hands", "humanoid_robotics", ['Everwin Precision 长盈精密', '300115.SZ', '长盈精密']),
    _frontier("6481t_hum", 'THK Co.', '6481.T', "JP", "hum_hands", "humanoid_robotics", ['THK Co.', '6481.T']),
    # --- hum_materials (tier 7) ---
    _frontier("688295ss_hum", 'Zhongfu Shenying (中复神鹰)', '688295.SS', "CN", "hum_materials", "humanoid_robotics", ['Zhongfu Shenying (中复神鹰)', '688295.SS', '中复神鹰']),
    _frontier("002085sz_hum", 'Wanfeng Auto Holding (万丰奥威)', '002085.SZ', "CN", "hum_materials", "humanoid_robotics", ['Wanfeng Auto Holding (万丰奥威)', '002085.SZ', '万丰奥威']),
    _frontier("603305ss_hum", 'Xusheng Group (旭升集团)', '603305.SS', "CN", "hum_materials", "humanoid_robotics", ['Xusheng Group (旭升集团)', '603305.SS', '旭升集团']),
    _frontier("600933ss_hum", 'IKD Co. (爱柯迪)', '600933.SS', "CN", "hum_materials", "humanoid_robotics", ['IKD Co. (爱柯迪)', '600933.SS', '爱柯迪']),
    _frontier("002886sz_hum", 'Wote Advanced Materials (沃特股份)', '002886.SZ', "CN", "hum_materials", "humanoid_robotics", ['Wote Advanced Materials (沃特股份)', '002886.SZ', '沃特股份']),
    # --- hum_oem (tier 8) ---
    _frontier("tsla_hum", 'Tesla', 'TSLA', "US", "hum_oem", "humanoid_robotics", ['Tesla', 'TSLA']),
    _frontier("601138ss_hum", 'Foxconn Industrial Internet 工业富联', '601138.SS', "CN", "hum_oem", "humanoid_robotics", ['Foxconn Industrial Internet 工业富联', '601138.SS', '工业富联']),
    _frontier("005380ks_hum", 'Hyundai Motor', '005380.KS', "KR", "hum_oem", "humanoid_robotics", ['Hyundai Motor', '005380.KS']),
    _frontier("688585ss_hum", 'Shanwei New Material 上纬新材 (AgiBot/智元 shell)', '688585.SS', "CN", "hum_oem", "humanoid_robotics", ['Shanwei New Material 上纬新材 (AgiBot/智元 shell)', '688585.SS', '上纬新材']),
    _frontier("000157sz_hum", 'Zoomlion 中联重科', '000157.SZ', "CN", "hum_oem", "humanoid_robotics", ['Zoomlion 中联重科', '000157.SZ', '中联重科']),
    _frontier("277810kq_hum", 'Rainbow Robotics', '277810.KQ', "KR", "hum_oem", "humanoid_robotics", ['Rainbow Robotics', '277810.KQ']),
    _frontier("9880hk_hum", 'UBTECH Robotics 优必选', '9880.HK', "HK", "hum_oem", "humanoid_robotics", ['UBTECH Robotics 优必选', '9880.HK', '优必选']),
    _frontier("002747sz_hum", 'Estun Automation 埃斯顿', '002747.SZ', "CN", "hum_oem", "humanoid_robotics", ['Estun Automation 埃斯顿', '002747.SZ', '埃斯顿']),
    _frontier("300024sz_hum", 'Siasun Robot & Automation 新松机器人', '300024.SZ', "CN", "hum_oem", "humanoid_robotics", ['Siasun Robot & Automation 新松机器人', '300024.SZ', '新松机器人']),
]


def _consumer(cid, name, ticker, seg, theme, aliases, region="US") -> dict:
    """A US-listed consumer name for a cycle theme. No chain_role semantics / no
    SEED_EDGES — the segment's CycleProfile (inherited via `seg`) is its axis."""
    return {"id": cid, "name": name, "tickers": [ticker], "aliases": aliases, "region": region,
            "chain_role": seg, "cn_code": None, "themes": [theme], "seg": {theme: seg}}


# --- internet companies (US-listed; excl. non-US-cycle names PDD/BABA/JD/SE/MELI/CPNG) ---
INTERNET_COMPANIES = [
    _consumer("googl", "Alphabet", "GOOGL", "net_search_ads", "internet", ["Alphabet", "Google", "GOOGL"]),
    _consumer("zillow", "Zillow Group", "ZG", "net_search_ads", "internet", ["Zillow", "ZG", "Z"]),
    _consumer("meta", "Meta Platforms", "META", "net_social", "internet", ["Meta", "Facebook", "Instagram", "META"]),
    _consumer("pins", "Pinterest", "PINS", "net_social", "internet", ["Pinterest", "PINS"]),
    _consumer("snap", "Snap", "SNAP", "net_social", "internet", ["Snap", "Snapchat", "SNAP"]),
    _consumer("rddt", "Reddit", "RDDT", "net_social", "internet", ["Reddit", "RDDT"]),
    _consumer("mtch", "Match Group", "MTCH", "net_social", "internet", ["Match Group", "Tinder", "MTCH"]),
    _consumer("bmbl", "Bumble", "BMBL", "net_social", "internet", ["Bumble", "BMBL"]),
    _consumer("nflx", "Netflix", "NFLX", "net_streaming", "internet", ["Netflix", "NFLX"]),
    _consumer("spot", "Spotify", "SPOT", "net_streaming", "internet", ["Spotify", "SPOT"]),
    _consumer("roku", "Roku", "ROKU", "net_streaming", "internet", ["Roku", "ROKU"]),
    _consumer("duol", "Duolingo", "DUOL", "net_streaming", "internet", ["Duolingo", "DUOL"]),
    _consumer("amzn", "Amazon", "AMZN", "net_ecommerce", "internet", ["Amazon", "AMZN"]),
    _consumer("ebay", "eBay", "EBAY", "net_ecommerce", "internet", ["eBay", "EBAY"]),
    _consumer("etsy", "Etsy", "ETSY", "net_ecommerce", "internet", ["Etsy", "ETSY"]),
    _consumer("chwy", "Chewy", "CHWY", "net_ecommerce", "internet", ["Chewy", "CHWY"]),
    _consumer("wayfair", "Wayfair", "W", "net_ecommerce", "internet", ["Wayfair", "W"]),
    _consumer("shop", "Shopify", "SHOP", "net_ecommerce", "internet", ["Shopify", "SHOP"]),
    _consumer("uber", "Uber Technologies", "UBER", "net_gig", "internet", ["Uber", "UBER"]),
    _consumer("lyft", "Lyft", "LYFT", "net_gig", "internet", ["Lyft", "LYFT"]),
    _consumer("dash", "DoorDash", "DASH", "net_gig", "internet", ["DoorDash", "DASH"]),
    _consumer("cart", "Instacart (Maplebear)", "CART", "net_gig", "internet", ["Instacart", "Maplebear", "CART"]),
    _consumer("bkng", "Booking Holdings", "BKNG", "net_travel", "internet", ["Booking", "Booking.com", "Priceline", "BKNG"]),
    _consumer("expe", "Expedia Group", "EXPE", "net_travel", "internet", ["Expedia", "EXPE"]),
    _consumer("abnb", "Airbnb", "ABNB", "net_travel", "internet", ["Airbnb", "ABNB"]),
    _consumer("pypl", "PayPal", "PYPL", "net_fintech", "internet", ["PayPal", "PYPL"]),
    # NOTE: Block rebranded its NYSE ticker SQ→XYZ (effective 2025-01-21). XYZ is current — do not "fix" back to SQ.
    _consumer("block", "Block", "XYZ", "net_fintech", "internet", ["Block", "Square", "Cash App", "XYZ"]),
    _consumer("afrm", "Affirm", "AFRM", "net_fintech", "internet", ["Affirm", "AFRM"]),
    _consumer("rblx", "Roblox", "RBLX", "net_gaming", "internet", ["Roblox", "RBLX"]),
    _consumer("ttwo", "Take-Two Interactive", "TTWO", "net_gaming", "internet", ["Take-Two", "Rockstar", "TTWO"]),
]

# --- retail companies (US-listed; ret_discount = counter-cyclical trade-down winners) ---
RETAIL_COMPANIES = [
    _consumer("wmt", "Walmart", "WMT", "ret_discount", "retail", ["Walmart", "WMT"]),
    _consumer("cost", "Costco Wholesale", "COST", "ret_discount", "retail", ["Costco", "COST"]),
    _consumer("bjs", "BJ's Wholesale Club", "BJ", "ret_discount", "retail", ["BJ's", "BJ's Wholesale", "BJ"]),
    _consumer("tjx", "TJX Companies", "TJX", "ret_discount", "retail", ["TJX", "TJ Maxx", "Marshalls", "TJX"]),
    _consumer("ross", "Ross Stores", "ROST", "ret_discount", "retail", ["Ross", "Ross Stores", "ROST"]),
    _consumer("burl", "Burlington Stores", "BURL", "ret_discount", "retail", ["Burlington", "BURL"]),
    _consumer("ollie", "Ollie's Bargain Outlet", "OLLI", "ret_discount", "retail", ["Ollie's", "OLLI"]),
    _consumer("five", "Five Below", "FIVE", "ret_discount", "retail", ["Five Below", "FIVE"]),
    _consumer("dg", "Dollar General", "DG", "ret_discount", "retail", ["Dollar General", "DG"]),
    _consumer("dltr", "Dollar Tree", "DLTR", "ret_discount", "retail", ["Dollar Tree", "Family Dollar", "DLTR"]),
    _consumer("kr", "Kroger", "KR", "ret_grocery", "retail", ["Kroger", "KR"]),
    _consumer("aci", "Albertsons", "ACI", "ret_grocery", "retail", ["Albertsons", "ACI"]),
    _consumer("sfm", "Sprouts Farmers Market", "SFM", "ret_grocery", "retail", ["Sprouts", "SFM"]),
    _consumer("azo", "AutoZone", "AZO", "ret_auto_parts", "retail", ["AutoZone", "AZO"]),
    _consumer("orly", "O'Reilly Automotive", "ORLY", "ret_auto_parts", "retail", ["O'Reilly", "ORLY"]),
    _consumer("gap", "Gap", "GAP", "ret_apparel", "retail", ["Gap", "Old Navy", "GAP"]),
    _consumer("anf", "Abercrombie & Fitch", "ANF", "ret_apparel", "retail", ["Abercrombie", "ANF"]),
    _consumer("aeo", "American Eagle Outfitters", "AEO", "ret_apparel", "retail", ["American Eagle", "AEO"]),
    _consumer("urbn", "Urban Outfitters", "URBN", "ret_apparel", "retail", ["Urban Outfitters", "Anthropologie", "URBN"]),
    _consumer("lulu", "Lululemon Athletica", "LULU", "ret_apparel", "retail", ["Lululemon", "LULU"]),
    _consumer("bby", "Best Buy", "BBY", "ret_electronics", "retail", ["Best Buy", "BBY"]),
    _consumer("hd", "Home Depot", "HD", "ret_home_improve", "retail", ["Home Depot", "HD"]),
    _consumer("low", "Lowe's", "LOW", "ret_home_improve", "retail", ["Lowe's", "LOW"]),
    _consumer("tgt", "Target", "TGT", "ret_specialty", "retail", ["Target", "TGT"]),
    _consumer("ulta", "Ulta Beauty", "ULTA", "ret_specialty", "retail", ["Ulta", "Ulta Beauty", "ULTA"]),
    _consumer("dks", "Dick's Sporting Goods", "DKS", "ret_specialty", "retail", ["Dick's", "DKS"]),
    _consumer("tsco", "Tractor Supply", "TSCO", "ret_specialty", "retail", ["Tractor Supply", "TSCO"]),
    _consumer("rh", "RH (Restoration Hardware)", "RH", "ret_specialty", "retail", ["RH", "Restoration Hardware"]),
    _consumer("wsm", "Williams-Sonoma", "WSM", "ret_specialty", "retail", ["Williams-Sonoma", "Pottery Barn", "WSM"]),
    _consumer("kmx", "CarMax", "KMX", "ret_specialty", "retail", ["CarMax", "KMX"]),
]

# --- restaurant companies (US-listed; rst_qsr = counter-cyclical trade-down) ---
RESTAURANT_COMPANIES = [
    _consumer("mcd", "McDonald's", "MCD", "rst_qsr", "restaurants", ["McDonald's", "MCD"]),
    _consumer("wen", "Wendy's", "WEN", "rst_qsr", "restaurants", ["Wendy's", "WEN"]),
    _consumer("yum", "Yum! Brands", "YUM", "rst_qsr", "restaurants", ["Yum Brands", "KFC", "Taco Bell", "Pizza Hut", "YUM"]),
    _consumer("qsr", "Restaurant Brands Intl", "QSR", "rst_qsr", "restaurants", ["Restaurant Brands", "Burger King", "Tim Hortons", "QSR"]),
    _consumer("jack", "Jack in the Box", "JACK", "rst_qsr", "restaurants", ["Jack in the Box", "JACK"]),
    _consumer("loco", "El Pollo Loco", "LOCO", "rst_qsr", "restaurants", ["El Pollo Loco", "LOCO"]),
    _consumer("dpz", "Domino's Pizza", "DPZ", "rst_pizza_delivery", "restaurants", ["Domino's", "DPZ"]),
    _consumer("pzza", "Papa John's", "PZZA", "rst_pizza_delivery", "restaurants", ["Papa John's", "PZZA"]),
    _consumer("cmg", "Chipotle Mexican Grill", "CMG", "rst_fast_casual", "restaurants", ["Chipotle", "CMG"]),
    _consumer("cava", "CAVA Group", "CAVA", "rst_fast_casual", "restaurants", ["CAVA", "CAVA Group"]),
    _consumer("sg", "Sweetgreen", "SG", "rst_fast_casual", "restaurants", ["Sweetgreen", "SG"]),
    _consumer("wing", "Wingstop", "WING", "rst_fast_casual", "restaurants", ["Wingstop", "WING"]),
    _consumer("shak", "Shake Shack", "SHAK", "rst_fast_casual", "restaurants", ["Shake Shack", "SHAK"]),
    _consumer("sbux", "Starbucks", "SBUX", "rst_coffee_snack", "restaurants", ["Starbucks", "SBUX"]),
    _consumer("bros", "Dutch Bros", "BROS", "rst_coffee_snack", "restaurants", ["Dutch Bros", "BROS"]),
    _consumer("dri", "Darden Restaurants", "DRI", "rst_casual_dining", "restaurants", ["Darden", "Olive Garden", "DRI"]),
    _consumer("txrh", "Texas Roadhouse", "TXRH", "rst_casual_dining", "restaurants", ["Texas Roadhouse", "TXRH"]),
    _consumer("eat", "Brinker International", "EAT", "rst_casual_dining", "restaurants", ["Brinker", "Chili's", "EAT"]),
    _consumer("dine", "Dine Brands Global", "DIN", "rst_casual_dining", "restaurants", ["Dine Brands", "Applebee's", "IHOP", "DIN"]),
    _consumer("bloomin", "Bloomin' Brands", "BLMN", "rst_casual_dining", "restaurants", ["Bloomin' Brands", "Outback", "BLMN"]),
    _consumer("cake", "Cheesecake Factory", "CAKE", "rst_casual_dining", "restaurants", ["Cheesecake Factory", "CAKE"]),
    _consumer("cbrl", "Cracker Barrel", "CBRL", "rst_casual_dining", "restaurants", ["Cracker Barrel", "CBRL"]),
    _consumer("play", "Dave & Buster's", "PLAY", "rst_casual_dining", "restaurants", ["Dave & Buster's", "PLAY"]),
    _consumer("fwrg", "First Watch", "FWRG", "rst_casual_dining", "restaurants", ["First Watch", "FWRG"]),
    _consumer("stks", "The ONE Group (STK)", "STKS", "rst_fine_dining", "restaurants", ["The ONE Group", "STK", "STKS"]),
]

COMPANIES: list[dict] = (
    OPTICAL_COMPANIES + SHARED_COMPANIES + CHIP_COMPANIES + SOFTWARE_COMPANIES
    + SPACE_COMPANIES + ROBOT_COMPANIES
    + INTERNET_COMPANIES + RETAIL_COMPANIES + RESTAURANT_COMPANIES
)

# Bulk theme universe (US ≥$2B + JP/KR/TW), generated by scripts/universe_build.py
# and gated against the authoritative Finnhub exchange symbol sets. Appended when
# present; absent in a fresh checkout so the curated core stays turnkey/testable.
try:
    from .universe import UNIVERSE as _UNIVERSE

    COMPANIES = COMPANIES + _UNIVERSE
except ImportError:
    _UNIVERSE = []  # optional generated artifact — absent in a fresh checkout
except Exception as _e:  # corrupt/truncated universe.py must NOT silently shrink the basket
    from ..logging import get_logger

    get_logger("xar.registry").warning("universe.py present but failed to load (%s); "
                                        "running with curated core only", _e)
    _UNIVERSE = []

# --- Seed TechRoute nodes --------------------------------------------------
TECH_ROUTES: list[dict] = [
    # optical
    {"id": "tr_800g", "name": "800G", "attrs": {"speed_gen": "800G"}},
    {"id": "tr_1600g", "name": "1.6T", "attrs": {"speed_gen": "1.6T"}},
    {"id": "tr_cpo", "name": "CPO", "attrs": {"family": "co-packaged optics"}},
    {"id": "tr_lpo", "name": "LPO", "attrs": {"family": "linear-drive, DSP-less"}},
    {"id": "tr_siph", "name": "Silicon Photonics", "attrs": {"family": "SiPh"}},
    {"id": "tr_eml", "name": "EML", "attrs": {"family": "laser chip"}},
    # chip
    {"id": "tr_euv", "name": "EUV", "attrs": {"family": "EUV lithography"}},
    {"id": "tr_2nm", "name": "2nm GAA", "attrs": {"family": "leading-edge node"}},
    {"id": "tr_cowos", "name": "CoWoS", "attrs": {"family": "2.5D advanced packaging"}},
    {"id": "tr_hbm", "name": "HBM", "attrs": {"family": "high-bandwidth memory"}},
    {"id": "tr_chiplet", "name": "Chiplet / UCIe", "attrs": {"family": "chiplet interconnect"}},
    # ai_software — AI capability "routes" enterprises adopt
    {"id": "tr_ai_agents", "name": "AI Agents", "attrs": {"family": "autonomous agents"}},
    {"id": "tr_copilots", "name": "Copilots", "attrs": {"family": "assistive copilots"}},
    {"id": "tr_rag", "name": "RAG / Enterprise Search", "attrs": {"family": "retrieval"}},
    {"id": "tr_genai_infra", "name": "GenAI Infra / LLMOps", "attrs": {"family": "model ops"}},
    # space_exploration tech routes
    {"id": "tr_reusable", "name": "Reusable Launch", "attrs": {"family": "可复用运载"}},
    {"id": "tr_methalox", "name": "Methalox Propulsion", "attrs": {"family": "甲烷推进"}},
    {"id": "tr_megaconstellation", "name": "Mega-constellation", "attrs": {"family": "巨型星座"}},
    {"id": "tr_orbital_compute", "name": "Orbital Compute", "attrs": {"family": "在轨算力"}},
    {"id": "tr_electric_prop", "name": "Electric Propulsion", "attrs": {"family": "电推进"}},
    # humanoid_robotics tech routes
    {"id": "tr_harmonic", "name": "Harmonic Reducer", "attrs": {"family": "谐波减速"}},
    {"id": "tr_roller_screw", "name": "Planetary Roller Screw", "attrs": {"family": "行星滚柱丝杠"}},
    {"id": "tr_frameless", "name": "Frameless Torque Motor", "attrs": {"family": "无框力矩电机"}},
    {"id": "tr_vla", "name": "VLA Embodied Model", "attrs": {"family": "具身大模型"}},
    {"id": "tr_tactile", "name": "Tactile Sensing", "attrs": {"family": "触觉传感"}},
]

# --- Seed structural edges (bootstraps each chain's graph backbone) ---------
SEED_EDGES: list[tuple[str, str, str]] = [
    # ai_optical
    ("nvidia", "coherent", EdgeType.INVESTS_IN.value),
    ("nvidia", "lumentum", EdgeType.INVESTS_IN.value),
    ("marvell", "innolight", EdgeType.SUPPLIES.value),
    ("lumentum", "innolight", EdgeType.SUPPLIES.value),
    ("innolight", "nvidia", EdgeType.SUPPLIES.value),
    ("eoptolink", "nvidia", EdgeType.SUPPLIES.value),
    ("tr_cpo", "tr_lpo", EdgeType.COMPETES_WITH.value),
    ("tr_siph", "tr_eml", EdgeType.SUBSTITUTES.value),
    ("tr_cpo", "tr_800g", EdgeType.SUBSTITUTES.value),
    # ai_chip — equipment/materials -> foundry
    ("asml", "tsmc", EdgeType.SUPPLIES.value),
    ("amat", "tsmc", EdgeType.SUPPLIES.value),
    ("lamresearch", "tsmc", EdgeType.SUPPLIES.value),
    ("klac", "tsmc", EdgeType.SUPPLIES.value),
    ("tokyoelectron", "tsmc", EdgeType.SUPPLIES.value),
    ("shinetsu", "tsmc", EdgeType.SUPPLIES.value),
    ("sumco", "tsmc", EdgeType.SUPPLIES.value),
    ("cadence", "nvidia", EdgeType.SUPPLIES.value),
    ("synopsys", "tsmc", EdgeType.SUPPLIES.value),
    ("arm", "qualcomm", EdgeType.SUPPLIES.value),
    # foundry/memory/packaging -> GPU/CPU
    ("tsmc", "nvidia", EdgeType.SUPPLIES.value),
    ("tsmc", "amd", EdgeType.SUPPLIES.value),
    ("skhynix", "nvidia", EdgeType.SUPPLIES.value),
    ("micron", "nvidia", EdgeType.SUPPLIES.value),
    ("samsung", "nvidia", EdgeType.SUPPLIES.value),
    ("ase", "nvidia", EdgeType.SUPPLIES.value),
    ("amkor", "amd", EdgeType.SUPPLIES.value),
    ("shengyi", "nvidia", EdgeType.SUPPLIES.value),
    ("skhynix", "micron", EdgeType.COMPETES_WITH.value),
    ("amd", "nvidia", EdgeType.COMPETES_WITH.value),
    ("intel", "amd", EdgeType.COMPETES_WITH.value),
    # tech routes
    ("tsmc", "tr_2nm", EdgeType.USES_TECHROUTE.value),
    ("tsmc", "tr_cowos", EdgeType.USES_TECHROUTE.value),
    ("asml", "tr_euv", EdgeType.USES_TECHROUTE.value),
    ("skhynix", "tr_hbm", EdgeType.USES_TECHROUTE.value),
    ("nvidia", "tr_cowos", EdgeType.USES_TECHROUTE.value),
    ("nvidia", "tr_hbm", EdgeType.USES_TECHROUTE.value),
    ("amd", "tr_chiplet", EdgeType.USES_TECHROUTE.value),
]

# --- ai_software adoption-wave tech-route edges (auto-generated) ---
SEED_EDGES += [
    ("ibm", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("ibm", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("net", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("net", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("team", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("team", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("docn", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("docn", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("ntnx", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("ntnx", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("frog", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("frog", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("path", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("path", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("gtlb", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("gtlb", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("fsly", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("fsly", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("ddog", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("dt", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("ntct", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("orcl", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("orcl", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("pltr", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("pltr", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("snow", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("snow", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("mdb", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("mdb", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("cflt", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("cflt", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("infa", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("infa", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("estc", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("estc", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("tdc", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("tdc", "tr_genai_infra", EdgeType.USES_TECHROUTE.value),
    ("panw", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("crwd", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("ftnt", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("zs", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("ffiv", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("cybr", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("okta", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("akam", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("gen", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("rbrk", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("chkp", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("sail", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("s", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("qlys", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("vrns", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("tenb", "tr_ai_agents", EdgeType.USES_TECHROUTE.value),
    ("msft", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("now", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("zm", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("docu", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("smar", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("dbx", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("mndy", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("box", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("rng", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("crm", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("hubs", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("zi", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("pega", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("frsh", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("app", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("adbe", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("twlo", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("gddy", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("ttd", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("zeta", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("kvyo", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("mgni", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("brze", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("ramp", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("wix", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("sap", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("adp", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("intu", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("wday", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("payx", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("day", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("payc", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("pcty", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("pycr", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("bill", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("wk", "tr_copilots", EdgeType.USES_TECHROUTE.value),
    ("veev", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("iot", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("tost", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("tyl", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("gwre", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("bsy", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("dsgx", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("manh", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("hqy", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("cwan", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("ttan", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("pcor", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("appf", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("docs", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("env", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("soun", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("qtwo", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("spns", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("agys", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("payo", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("alrm", "tr_rag", EdgeType.USES_TECHROUTE.value),
    ("pinc", "tr_rag", EdgeType.USES_TECHROUTE.value),
]

# --- space + humanoid adoption tech-route edges (auto-generated) ---
SEED_EDGES += [
    ("601100ss_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("601100ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("6594t_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("6594t_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("688017ss_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("688017ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("sha0de_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("sha0de_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("002472sz_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("002472sz_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("6324t_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("6324t_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("003021sz_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("003021sz_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("603667ss_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("603667ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("002896sz_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("002896sz_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("603009ss_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("603009ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("300580sz_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("300580sz_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("688160ss_hum", "tr_harmonic", EdgeType.USES_TECHROUTE.value),
    ("688160ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("ph_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("002008sz_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("600580ss_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("st_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("novt_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("603728ss_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("300503sz_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("002979sz_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("300660sz_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("688698ss_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("alnt_hum", "tr_frameless", EdgeType.USES_TECHROUTE.value),
    ("6981t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("6758t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("6861t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("stm_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("6762t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("603501ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("algm_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("688322ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("688213ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("688582ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("603662ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("300007sz_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("301413sz_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("605488ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("090710kq_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("2330tw_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("6723t_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("6702t_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("603893ss_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("9660hk_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("688099ss_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("300458sz_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("300496sz_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("amba_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("6526t_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("688088ss_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("601689ss_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("601689ss_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("6479t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("6479t_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("300115sz_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("300115sz_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("6481t_hum", "tr_tactile", EdgeType.USES_TECHROUTE.value),
    ("6481t_hum", "tr_roller_screw", EdgeType.USES_TECHROUTE.value),
    ("tsla_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("601138ss_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("005380ks_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("688585ss_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("000157sz_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("277810kq_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("9880hk_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("002747sz_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("300024sz_hum", "tr_vla", EdgeType.USES_TECHROUTE.value),
    ("rtx_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("rtx_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("ba_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("ba_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("airpa_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("airpa_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("safpa_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("safpa_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("lmt_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("lmt_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("7011t_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("7011t_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("noc_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("noc_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("rklb_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("rklb_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("7013t_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("7013t_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("600879ss_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("600879ss_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("fly_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("fly_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("lunr_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("lunr_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("avijf_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("avijf_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("000901sz_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("000901sz_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("aviomi_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("aviomi_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("lhx_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("lhx_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("012450ks_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("012450ks_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("600893ss_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("600893ss_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("moga_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("moga_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("krmn_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("krmn_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("600343ss_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("600343ss_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("003009sz_spa", "tr_methalox", EdgeType.USES_TECHROUTE.value),
    ("003009sz_spa", "tr_electric_prop", EdgeType.USES_TECHROUTE.value),
    ("688256ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("6503t_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("9432t_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("mchp_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("asts_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("002281sz_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("601698ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("603019ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("600118ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("300223sz_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("pl_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("688385ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("9412t_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("688568ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("bksy_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("s63si_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("6701t_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("mtsi_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("047810ks_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("ktos_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("vsat_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("qrvo_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("002405sz_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("wolf_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("3596tw_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("gilt_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("300571sz_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("hwm_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("crs_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("ati_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("002080sz_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("3402t_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("hxl_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("mtrn_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("688122ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("300699sz_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("3401t_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("600456ss_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("300034sz_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("mrnpa_spa", "tr_orbital_compute", EdgeType.USES_TECHROUTE.value),
    ("grmn_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("sats_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("hxgby_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("trmb_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("gsat_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("irdm_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("etlpa_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("002151sz_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("300045sz_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("satl_spa", "tr_megaconstellation", EdgeType.USES_TECHROUTE.value),
    ("gd_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("hopa_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("eslt_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("ldomi_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("saabbst_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
    ("voyg_spa", "tr_reusable", EdgeType.USES_TECHROUTE.value),
]

NODE_TYPE_BY_ROLE = {
    # optical roles
    "module_maker": NodeType.MODULE_MAKER.value,
    "contract_manufacturer": NodeType.MODULE_MAKER.value,
    "component": NodeType.UPSTREAM_COMPONENT.value,
    "customer": NodeType.DOWNSTREAM_CUSTOMER.value,
    # chip segment-roles
    "chip_equipment": NodeType.UPSTREAM_COMPONENT.value,
    "chip_materials": NodeType.UPSTREAM_COMPONENT.value,
    "chip_eda": NodeType.UPSTREAM_COMPONENT.value,
    "chip_foundry": NodeType.MODULE_MAKER.value,
    "chip_memory": NodeType.UPSTREAM_COMPONENT.value,
    "chip_gpu": NodeType.MODULE_MAKER.value,
    "chip_cpu": NodeType.MODULE_MAKER.value,
    "chip_packaging": NodeType.UPSTREAM_COMPONENT.value,
    "chip_pcb": NodeType.UPSTREAM_COMPONENT.value,
    # software segment-roles: enablers = upstream component; end-apps = downstream
    "swe_devinfra": NodeType.UPSTREAM_COMPONENT.value,
    "swe_observability": NodeType.UPSTREAM_COMPONENT.value,
    "swe_data": NodeType.UPSTREAM_COMPONENT.value,
    "swe_security": NodeType.UPSTREAM_COMPONENT.value,
    "swe_productivity": NodeType.DOWNSTREAM_CUSTOMER.value,
    "swe_crm": NodeType.DOWNSTREAM_CUSTOMER.value,
    "swe_marketing": NodeType.DOWNSTREAM_CUSTOMER.value,
    "swe_erp_hr": NodeType.DOWNSTREAM_CUSTOMER.value,
    "swe_vertical": NodeType.DOWNSTREAM_CUSTOMER.value,
    # space roles: launch/satellites/datacenter = makers; the rest upstream/downstream
    "spx_launch": NodeType.MODULE_MAKER.value,
    "spx_propulsion": NodeType.UPSTREAM_COMPONENT.value,
    "spx_satellites": NodeType.MODULE_MAKER.value,
    "spx_datacenter": NodeType.MODULE_MAKER.value,
    "spx_ground": NodeType.UPSTREAM_COMPONENT.value,
    "spx_components": NodeType.UPSTREAM_COMPONENT.value,
    "spx_apps": NodeType.DOWNSTREAM_CUSTOMER.value,
    "spx_defense": NodeType.DOWNSTREAM_CUSTOMER.value,
    # humanoid roles: components upstream; OEM integrator downstream
    "hum_actuation": NodeType.UPSTREAM_COMPONENT.value,
    "hum_motors": NodeType.UPSTREAM_COMPONENT.value,
    "hum_sensors": NodeType.UPSTREAM_COMPONENT.value,
    "hum_compute": NodeType.UPSTREAM_COMPONENT.value,
    "hum_power": NodeType.UPSTREAM_COMPONENT.value,
    "hum_hands": NodeType.UPSTREAM_COMPONENT.value,
    "hum_materials": NodeType.UPSTREAM_COMPONENT.value,
    "hum_oem": NodeType.DOWNSTREAM_CUSTOMER.value,
}


def company_by_id(cid: str) -> dict | None:
    return next((c for c in COMPANIES if c["id"] == cid), None)
